//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDonut.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeDonut.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Build {
            get {
                object obj = ResourceManager.GetObject("Build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BuildAndRun {
            get {
                object obj = ResourceManager.GetObject("BuildAndRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 #C AutoComplete
        ///#####
        ///Keyword===
        ///__int16
        ///__int32
        ///__int64
        ///__int8
        ///auto
        ///break
        ///case
        ///char
        ///const
        ///continue
        ///default
        ///define
        ///do
        ///double
        ///else
        ///enum
        ///extern
        ///float
        ///for
        ///goto
        ///if
        ///include
        ///int
        ///long
        ///long long
        ///register
        ///return
        ///short
        ///signed
        ///sizeof
        ///static
        ///struct
        ///switch
        ///typedef
        ///union
        ///unsigned
        ///void
        ///volatile
        ///while
        ///KeywordEnd;
        ///
        ///
        ///#####
        ///Functions===
        ///scanf(, )
        ///printf()
        ///
        ///sizeof()
        ///
        ///abs()
        ///ceil()
        ///fabs()
        ///floor()
        ///log()
        ///log10()
        ///pow(, )
        ///sqrt()
        ///
        ///strcat(, )
        ///strchr(, )
        ///strcmp(, )
        ///strcpy( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string C_AutoComplete {
            get {
                return ResourceManager.GetString("C_AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #C Highlighting code
        ///
        ///ClassName===\b(enum|struct|union)\s+(?&lt;range&gt;\w+?)\b
        ///
        ///Keyword===(\b(break|case|continue|default|do|else|enum|extern|for|goto|if|register|return|sizeof|switch|volatile|while)\b|\b(__int16|__int32|__int64|__int8|auto|char|const|double|float|int|long|short|signed|static|struct|typedef|union|unsigned|void)\b\s)
        ///
        ///Function===\b(scanf|printf|sizeof|abs|ceil|fabs|floor|log|log10|pow|sqrt|strcat|strchr|strcmp|strcpy|strlen|strstr|clearerr|fclose|feof|fgetc|fgets|fopen|fprintf|fputc|fputs| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string C_HighLighting {
            get {
                return ResourceManager.GetString("C_HighLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #include &lt;stdio.h&gt;
        ///#include &lt;stdlib.h&gt;
        ///
        ///int main()
        ///{
        ///    printf(&quot;Hello Code Donut!\n&quot;);
        ///	system(&quot;pause&quot;);
        ///    return 0;
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string CDefaultCode {
            get {
                return ResourceManager.GetString("CDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 #C++ AutoComplete
        ///#####
        ///Keyword===
        ///__int16
        ///__int32
        ///__int64
        ///__int8
        ///bool
        ///break
        ///case
        ///char
        ///cin
        ///class
        ///const
        ///continue
        ///cout
        ///defalut
        ///delete
        ///do
        ///double
        ///else
        ///enum
        ///false
        ///float
        ///for
        ///goto
        ///if
        ///include
        ///int
        ///list
        ///long
        ///long long
        ///map
        ///namespace
        ///new
        ///pragma
        ///queue
        ///return
        ///set
        ///short
        ///signed
        ///stack
        ///string
        ///struct
        ///struct
        ///switch
        ///true
        ///undef
        ///unsigned
        ///using
        ///vector
        ///wchar
        ///wchar_t
        ///while
        ///KeywordEnd;
        ///
        ///
        ///#####
        ///Functions===
        ///scanf(, )
        ///printf()
        ///
        ///sizeof()
        ///
        ///abs()
        ///ceil()
        ///fabs()
        ///floor()
        ///log [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cpp_AutoComplete {
            get {
                return ResourceManager.GetString("Cpp_AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #C++ Highlighting code
        ///
        ///ClassName===\b(class|struct|enum|interface)\s+(?&lt;range&gt;\w+?)\b
        ///
        ///Keyword===(\b(LRESULT|CString|String|WORD|DWORD|TCHAR|BYTE|BOOL|if|else|switch|case|break|defalut|return|true|false|for|do|while|continue|goto|cout|cin|endl)\b|\b(unsigned|signed|int|bool|char|short|long|float|double|wchar|wchar_t|__int8|__int16|__int32|__int64|struct|class|enum|interface|new|using|namespace|private|protected|public|const|delete)\b\s)
        ///
        ///Function===\b(scanf|printf|sizeof|abs|ceil|fabs|floor|log|log10 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Cpp_HighLighting {
            get {
                return ResourceManager.GetString("Cpp_HighLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #include &lt;iostream&gt;
        ///#include &lt;cstdlib&gt;
        ///using namespace std;
        ///
        ///int main()
        ///{
        ///    cout &lt;&lt; &quot;Hello Code Donut!&quot; &lt;&lt; endl;
        ///	system(&quot;pause&quot;);
        ///    return 0;
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string CppDefaultCode {
            get {
                return ResourceManager.GetString("CppDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Donut {
            get {
                object obj = ResourceManager.GetObject("Donut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 #简体中文
        ///
        ///##Form_Main
        ///File=文件
        ///New=新文件
        ///C File=C语言文件
        ///C++ File=C++文件
        ///Open=打开
        ///Save=保存
        ///SaveAs=另存为
        ///CheckUpdate=检查更新
        ///About=关于
        ///Exit=退出
        ///
        ///Edit=编辑
        ///Undo=撤销
        ///Redo=重做
        ///Cut=剪切
        ///Copy=复制
        ///Paste=粘贴
        ///Delete=删除
        ///DeleteCurrentLine=删除当前行
        ///DeleteAll=删除全部
        ///SelectAll=选择全部
        ///
        ///Search=搜索
        ///Find=寻找
        ///Replace=替换
        ///
        ///Build=构建
        ///Run=运行
        ///Build And Run=构建并运行
        ///
        ///Bug Report=错误反馈
        ///
        ///New C++File=新C++文件
        ///Open File=打开文件
        ///Save File=保存文件
        ///
        ///
        ///##Form_Find
        ///Find=寻找
        ///Find What:=寻找内容:
        ///&lt;&lt;Next=&lt;&lt;上一个
        ///Next&gt;&gt;=下一个&gt;&gt;
        ///Count=计数
        ///
        ///
        ///##Form_Replace
        ///R [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Lang_zh_cn {
            get {
                return ResourceManager.GetString("Lang_zh_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NewFile {
            get {
                object obj = ResourceManager.GetObject("NewFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SaveFile {
            get {
                object obj = ResourceManager.GetObject("SaveFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
